### ISSUE TITLE
Error Migrate Production

### ISSUE THREAD

**Issue by hugocc** [yossiedri/Redmine-Admin-Monitor-Plugin#1]
Hi, when i execute it, display it error, thanks.

bash-4.1$ sudo rake redmine:plugins:migrate RAILS_ENV=production
(in /btf/redmine)
rake aborted!
SyntaxError: /btf/redmine/plugins/Redmine-Admin-Monitor-Plugin/lib/redmine_admin_monitor/patches/application_controller_patch.rb:8: syntax error, unexpected ':', expecting kEND
          rescue_from Exception, with: :render_500 
                                      ^
/btf/redmine/plugins/Redmine-Admin-Monitor-Plugin/init.rb:18:in `_callback_before_83'
/btf/redmine/config/environment.rb:14
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)

**Comment by hugocc** [comment]
some comment?

**Comment by yossiedri** [comment]
fix it: rescue_from Exception, :with => :render_500

**Comment by hugocc** [comment]
thaks for your help, but now after intalled and try to use it with tab, display its errors in log...

Started GET "/admin_monitor_alerts?conditions=false" for 172.16.0.106 at Tue Sep 30 06:03:39 -0600 2014

SyntaxError (/btf/redmine/plugins/redmine_admin_monitor/app/controllers/admin_monitor_alerts_controller.rb:3: syntax error, unexpected ':', expecting kEND
...set_admin_monitor_alert, only: [:edit, :update, :destroy,:is...
                              ^
/btf/redmine/plugins/redmine_admin_monitor/app/controllers/admin_monitor_alerts_controller.rb:43: syntax error, unexpected ':', expecting '}'
        format.html { render action: 'edit' }
                                    ^
/btf/redmine/plugins/redmine_admin_monitor/app/controllers/admin_monitor_alerts_controller.rb:44: syntax error, unexpected ':', expecting '}'
...    format.json { render json: @admin_monitor_alert.errors, ...
                              ^
/btf/redmine/plugins/redmine_admin_monitor/app/controllers/admin_monitor_alerts_controller.rb:44: syntax error, unexpected ':', expecting '='
..._monitor_alert.errors, status: :unprocessable_entity }
                              ^
/btf/redmine/plugins/redmine_admin_monitor/app/controllers/admin_monitor_alerts_controller.rb:54: syntax error, unexpected ':', expecting kEND
        render json: @admin_monitor_alert.errors, ...
                    ^
/btf/redmine/plugins/redmine_admin_monitor/app/controllers/admin_monitor_alerts_controller.rb:54: syntax error, unexpected ':', expecting '='
..._monitor_alert.errors, status: :unprocessable_entity
                              ^
/btf/redmine/plugins/redmine_admin_monitor/app/controllers/admin_monitor_alerts_controller.rb:79: syntax error, unexpected ':', expecting '}'
...n_monitor_alerts_path, notice: 'Admin alert was successfully...
                              ^
/btf/redmine/plugins/redmine_admin_monitor/app/controllers/admin_monitor_alerts_controller.rb:80: syntax error, unexpected ':', expecting '}'
...  format.json { render action: 'edit', status: :created, loc...
                              ^
/btf/redmine/plugins/redmine_admin_monitor/app/controllers/admin_monitor_alerts_controller.rb:80: syntax error, unexpected ',', expecting '}'
....json { render action: 'edit', status: :created, location: @...
                              ^
/btf/redmine/plugins/redmine_admin_monitor/app/controllers/admin_monitor_alerts_controller.rb:82: syntax error, unexpected ':', expecting '}'
        format.html { render action: 'new' }
                                    ^
/btf/redmine/plugins/redmine_admin_monitor/app/controllers/admin_monitor_alerts_controller.rb:83: syntax error, unexpected ':', expecting '}'
...    format.json { render json: @admin_monitor_alert.errors, ...
                              ^
/btf/redmine/plugins/redmine_admin_monitor/app/controllers/admin_monitor_alerts_controller.rb:83: syntax error, unexpected ':', expecting '='
..._monitor_alert.errors, status: :unprocessable_entity }
                              ^
/btf/redmine/plugins/redmine_admin_monitor/app/controllers/admin_monitor_alerts_controller.rb:91: syntax error, unexpected ':', expecting '}'
..._monitor_alerts_path , notice: 'Admin alertwas successfully ...
                              ^
/btf/redmine/plugins/redmine_admin_monitor/app/controllers/admin_monitor_alerts_controller.rb:94: syntax error, unexpected ':', expecting '}'
        format.html { render action: 'edit' }
                                    ^
/btf/redmine/plugins/redmine_admin_monitor/app/controllers/admin_monitor_alerts_controller.rb:95: syntax error, unexpected ':', expecting '}'
...    format.json { render json: @admin_monitor_alert.errors, ...
                              ^
/btf/redmine/plugins/redmine_admin_monitor/app/controllers/admin_monitor_alerts_controller.rb:95: syntax error, unexpected ':', expecting '='
..._monitor_alert.errors, status: :unprocessable_entity }
                              ^):
