### ISSUE TITLE
Mass-assign protected attributes error. 

### ISSUE THREAD

**Issue by shawndibble** [yossiedri/Redmine-Admin-Monitor-Plugin#9]
This is for Redmine 3.1

Started GET "/admin_monitor_alerts?conditions=false" for 192.168.1.58 at 2015-08-19 08:48:22 -0500
Processing by AdminMonitorAlertsController#index as HTML
  Parameters: {"conditions"=>"false"}
  Current user: sdibble (id=427)
  Rendered plugins/redmine_admin_monitor/app/views/admin_monitor_alerts/index.html.erb within layouts/base (7.9ms)
WARNING: Can't mass-assign protected attributes for AdminMonitorAlert: counter

DEPRECATION WARNING: Mailer.deliver_alert_error_message(_args) is deprecated. Use Mailer.alert_error_message(_args).deliver instead. (called from method_missing at /var/data/redmine/app/models/mailer.rb:467)

**Comment by xJom** [comment]
Add :counter to line 15 in admin_monitor_alert.rb

```
attr_accessible :counter,:handle_flag,:backtrace,:user_id,:project_id,:issue_id,:alert_type,:source,:action,:message,:silent_flag
```
